### ISSUE TITLE
Modelagem de Requisitos - Cenários

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-de-Software/2019.2-Wire#35]
## Descrição da Issue
Desenvolver os cenários da aplicação Wire de acordo com a modelagem de requisitos.

### Tasks: 
- [x] Desenvolver cenários
- [x] Adicionar artefatos gerados à Wiki

### Critérios de aceitação

- [x] Validar com o grupo
- [x] Validar com o monitor

**Comment by caiovfernandes** [comment]
a

**Comment by caiovfernandes** [comment]
Issue finalizada.
