### ISSUE TITLE
Modelagem de Requisitos - Léxicos

### ISSUE THREAD

**Issue by sudjoao** [Requisitos-de-Software/2019.2-Wire#36]
## Descrição da Issue
Criar léxicos relacionados aos requisitos levantados para a aplicação Wire.
### Tasks:
- [x] Criar léxicos;
- [x] Definir como será organizado;
- [x] Adicionar à wiki do grupo.

### Critérios de aceitação
- [x] Ter léxicos que englobam todos os requisitos levantados;
- [x] Validação com o time;
- [x] Validação com o monitor.

**Comment by sudjoao** [comment]
O @lucasfcm9 e eu estamos reunidos fazendo esta issue, a parte dos objetos e estados já foi feita, agora iremos focar na parte dos verbos.
