### ISSUE TITLE
Modelagem de Requisitos - Casos de Uso

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#38]
## Descrição da Issue
Modelar os requisitos levantados em um diagrama de Casos de Uso e elaborar as Especificações de Uso de cada caso

### Tasks: 
- [x] Definir o que são Casos de Uso
- [x] Criar o diagrama de Casos de Uso dos RFs
- [x] Criar as Especificações de Uso para cada UC

### Critérios de aceitação
- [ ] Ter um diagrama completo, que englobe todos requisitos funcionais
- [ ] Diagrama e Especificações revisados pelos membros do grupo
- [ ] Diagrama e Especificações revisados pelo monitor

**Comment by iurisevero** [comment]
Para os Casos de Uso foi criado o seguinte diagrama:
![](https://i.imgur.com/MwkPOuS.png)

**Comment by iurisevero** [comment]
E foram definidas as seguintes Especificações

|Casos de Uso|Ator|Descrição|
|---|---|------|
|UC01 - Enviar mensagem| Usuário | Este caso de uso ocorre quando o usuário envia uma mensagem de texto ou de áudio para outro usuário|
|UC02 - Apagar mensagem| Usuário| Este caso de uso permite que o usuário apague uma mensagem enviada anteriormente|
|UC03 - Editar mensagem| Usuário | Este caso de uso ocorre quando o usuário deseja editar uma mensagem enviada|
|UC04 - Enviar arquivos| Usuário | Este caso de uso possibilita o usuário enviar arquivos externos, como .jpg, .pdf, entre outros tipos|
|UC05 - Fazer ligação| Usuário | Esse caso de uso permite o usuário se comunicar por meios além da mensagem|
|UC06 - Fazer ligação de vídeo| Usuário | Esse caso de uso fornece ao usuário a opção de ter uma conversa por vídeo com outro usuário|
|UC07 - Fazer ligação de áudio| Usuário | Esse caso permite ao usuário a opção de ter uma conversa por áudio com outro usuário|
|UC08 - Adicionar pessoas à chamada| Usuário | Este caso de uso ocorre quando o usuário adiciona uma terceira pessoas à chamada atual, seja de áudio ou de vídeo|
|UC09 - Criar grupo| Usuário| Este caso de uso permite que o usuário crie um grupo com outros usuários para que possam trocar mensagens|
|UC10 - Adicionar e remover pessoas do grupo| Usuário | Este caso de uso possibilita o usuário controlar as pessoas que estão no grupo|
|UC11 - Definir permissões de cada membro| Usuário | Esse caso de uso permite o usuário que criou o grupo definir as ações que outros membros do grupo podem executar|
|UC12 - Adicionar contatos| Usuário | Esse caso de uso fornece ao usuário a opção de salvar o número, nome de usuário e e-mail de outro usuário|
|UC13 - Editar dados do contato| Usuário | Esse caso permite ao usuário editar os dados de contatos salvos na plataforma operante|
|UC14 - Cadastrar usuário| Usuário | Esse caso de uso ocorre quando o usuário começa a usar o aplicativo e se cadastra pela primeira vez no mesmo, criando uma conta. É possível ter mais de uma conta|
|UC15 - Cadastrar por número de telefone| Usuário | Esse caso de uso fornece ao usuário a opção se cadastrar a partir do número de telefone utilizado|
|UC16 - Cadastrar por endereço de e-mail| Usuário | Esse caso de uso fornece ao usuário a opção se cadastrar a partir de um endereço de e-mail|
