### ISSUE TITLE
Elicitação de Requisitos - Subir todos os requisitos levantados

### ISSUE THREAD

**Issue by sudjoao** [Requisitos-de-Software/2019.2-Wire#43]
## Descrição da Issue
Passar para o GitHub Pages todas os requisitos levantados pelo grupo.
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar uma página para listar todos os requisitos.
- [x] Escrever todos os requisitos levantados.

### Critérios de aceitação
- [x] Validar com o grupo.

**Comment by sudjoao** [comment]
Todos os requisitos foram levantados e colocados na matriz, faltando apenas ser validado pelo grupo.
