### ISSUE TITLE
Modelagem de Requisitos - Refatorar Casos de Uso

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#44]
## Descrição da Issue
Refatorar os Casos de Uso de forma mais modularizada e completa.

### Tasks: .
- [x] Refazer o Diagrama de Casos de Uso
- [x] Criar novos diagramas para os módulos existentes
- [x] Atualizar as Especificações de Casos de Uso
- [x] Atualizar os Fluxos de Casos de Uso

### Critérios de aceitação
- [x] Grupo revisar as alterações feitas

**Comment by iurisevero** [comment]
Os diagramas de casos de uso podem ser vistos [aqui](https://drive.google.com/file/d/1TW3BCYjheSc-1ydT_dP5xLBB3eqAfdFq/view?usp=sharing). Refatorados e modularizados.

**Comment by iurisevero** [comment]
As novas especificações de uso são:


|Casos de Uso|Ator|Descrição|
|---|---|------|
|UC01 - Enviar mensagem| Usuário | Este caso de uso ocorre quando o usuário envia uma mensagem de texto ou de áudio para outro usuário|
|UC02 - Responder mensagem| Usuário| Este caso de uso permite que o usuário explicite para qual mensagem anterior a mensagem enviada no momento se refere |
|UC03 - Apagar mensagem| Usuário| Este caso de uso permite que o usuário apague uma mensagem enviada anteriormente|
|UC04 - Definir tempo de visualização da mensagem| Usuário | Este caso de uso permite ao usuário definir um período de tempo no qual a mensagem enviada ficará disponível para os outros usuários|
|UC05 - Enviar áudio | Usuário | Este caso de uso ocorre quando o usuário grava uma mensagem em um áudio e a envia para outro usuário|
|UC06 - Dar play e pause no áudio | Usuário | Este caso de uso permite o usuário parar e continuar a execução de um áudio recebido|
|UC07 - Escolher ponto de início do áudio | Usuário | Este caso de uso possibilita o usuário escolher em qual momento o áudio começará a ser reproduzido, possibilitando, também, avançar e retroceder o mesmo|
|UC08 - Editar mensagem| Usuário | Este caso de uso ocorre quando o usuário deseja editar uma mensagem enviada|
|UC09 - Encaminhar mensagem| Usuário | Este caso de uso permite ao usuário enviar uma mensagem recebida para outro usuário, sem alterar o remetente original|
|UC10 - Enviar arquivos| Usuário | Este caso de uso possibilita o usuário enviar arquivos externos, como .jpg, .pdf, entre outros tipos|
|UC11 - Abrir arquivo dentro do aplicativo| Usuário | Este caso de uso permite ao usuário abrir um arquivo recebido por mensagem sem sair do aplicativo|
|UC12 - Enviar imagem e vídeo| Usuário | Este caso de uso fornece ao usuário a opção de enviar arquivos de imagem e vídeo por mensagem|
|UC13 - Editar imagem| Usuário | Este caso de uso permite ao usuário editar uma imagem que será enviada|
|UC14 - Fazer backup de mensagens| Usuário | Este caso de uso possibilita o usuário salvar, em um banco de dados próprio, todas as conversas do aplicativo|
|UC15 - Fazer ligação| Usuário | Esse caso de uso permite o usuário se comunicar por meios além da mensagem|
|UC16 - Ligação de áudio| Usuário | Esse caso permite ao usuário a opção de ter uma conversa por áudio com outro usuário|
|UC17 - Ligar e desligar microfone| Usuário | Esse caso possibilita o usuário ligar e desligar o microfone, para que ele seja, ou não, escutado durante a ligação|
|UC18 - Entrar em ligação já existente| Usuário | Este caso de uso permite o usuário entrar em uma ligação, de áudio ou de vídeo, que está em execução|
|UC19 - Ligação de vídeo| Usuário | Esse caso de uso fornece ao usuário a opção de ter uma conversa por vídeo com outro usuário|
|UC20 - Ligar e desligar câmera| Usuário | Esse caso possibilita o usuário ligar e desligar a câmera de vídeo, para que ele seja, ou não, visto durante a ligação|
|UC21 - Adicionar pessoas à ligação| Usuário | Este caso de uso ocorre quando o usuário adiciona uma terceira pessoas à chamada atual, seja de áudio ou de vídeo|
|UC22 - Criar grupo| Usuário| Este caso de uso permite que o usuário crie um grupo com outros usuários para que possam trocar mensagens|
|UC23 - Fazer um grupo de Transmissão de mensagens| Usuário| Este caso de uso possibilita que o usuário transforme o grupo criado em um grupo de Transmissão de mensagens, ou seja, apenas pessoas com permissão podem enviar mensagens nele|
|UC24 - Adicionar e remover pessoas do grupo| Usuário | Este caso de uso fornece ao usuário o poder de adicionar e retirar as pessoas do grupo|
|UC25 - Definir permissões de cada membro| Usuário | Esse caso de uso permite o usuário que criou o grupo definir as ações que outros membros do grupo podem executar|
|UC26 - Fixar mensagens| Usuário | Esse caso de uso possibilita o usuário fixar um mensagem no topo do grupo, deixando-a visível para todos|
|UC27 - Silenciar grupo| Usuário | Esse caso de uso permite o usuário silenciar um grupo e não receber notificações do mesmo|
|UC28 - Enviar mensagem de alerta| Usuário | Esse caso de uso disponibiliza ao usuário uma mensagem de alerta, que ignora o silenciamento do grupo|
|UC29 - Responder mensagem recebida no grupo no privado| Usuário | Esse caso de uso permite o usuário responder uma mensagem enviada em um grupo diretamente na conversa privada dele com o usuário que a enviou|
|UC30 - Criar Guest Room| Usuário| Este caso de uso permite que o usuário crie Guest Room, que serve como uma extenção do mensageiro para usuários não cadastrados|
|UC31 - Gerar link externo para adicionar usuário| Usuário| Este caso de uso fornece ao usuário um link para que ele possa disponibilizar o Guest Room criado|
|UC32 - Fazer cadastro| Usuário | Esse caso de uso ocorre quando o usuário começa a usar o aplicativo e se cadastra pela primeira vez no mesmo, criando uma conta. É possível ter mais de uma conta|
|UC33 - Fazer cadastro pelo número de telefone| Usuário | Esse caso de uso fornece ao usuário a opção se cadastrar a partir do número de telefone utilizado|
|UC34 - Fazer cadastro pelo endereço de e-mail| Usuário | Esse caso de uso fornece ao usuário a opção se cadastrar a partir de um endereço de e-mail|
|UC35 - Definir nome de usuário| Usuário | Esse caso de uso permite o usuário definir o nome pelo qual será chamado dentro do aplicativo|
|UC36 - Criar um time| Usuário | Esse caso de uso possibilita ao usuário criar um time, ou seja, definir um grupo de usuário que tem mais contato com ele|
|UC37 - Criar um time| Usuário | Esse caso de uso permite o usuário adicionar pessoas ao time o qual ele pertence|
|UC38 - Adicionar contato de usuário| Usuário | Esse caso de uso fornece ao usuário a opção de salvar o número, nome de usuário e e-mail de outro usuário|
|UC39 - Editar dados do contato| Usuário | Esse caso de uso permite o usuário editar os dados de contatos salvos na plataforma operante|
|UC40 - Bloquear usuário| Usuário | Esse caso de uso possibilita ao usuário bloquear o acesso de outro usuário a ele|
|UC41 - Editar perfil| Usuário | Esse caso de uso permite o usuário alterar os dados inseridos em seu perfil|
|UC42 - Alterar opção de download automático| Usuário | Esse caso de uso ocorre quando o usuário desativa o download automático de arquivos, imagens, vídeos e/ou áudios|
|UC43 - Deletar conta| Usuário | Esse caso de uso permite que o usuário delete sua conta atual|
|UC43 - Mudar senha| Usuário | Esse caso de uso possibilita ao usuário mudar a senha de login da conta atual|

**Comment by iurisevero** [comment]
O fluxos de conversa ficaram definidos da seguinte forma:
### UC01 - Enviar Mensagem
#### Fluxo Básico

Usuário 1 envia uma mensagem de texto para o usuário 2

#### Fluxos Alternativos

#### FA1 - Responder mensagem

Usuário 1 responde uma mensagem que o usuário 2 havia enviado

#### FA2 - Apagar mensagem

Usuário 1 envia uma mensagem de texto para o usuário 2 e após algum tempo apaga a mensagem

#### FA3 - Definir tempo de visualização da mensagem

Usuário 1 define o tempo de visualização da mensagem para dez segundos e envia um texto para o usuário 2. Dez segundos após a mensagem ser visualizada, ela é automaticamente apagada.

#### FA4 - Enviar áudio

Usuário 1 envia uma mensagem de áudio para o usuário 2

#### FA5 - Escolher o ponto de início do áudio/ Dar play e pause no áudio

O usuário 2 pausa o áudio que havia recebido do usuário 1 e escolhe escutá-lo a partir dos últimos segundos.

#### FA6 - Editar mensagem

Usuário 1 envia uma mensagem de texto para o usuário 2 e depois edita o que estava escrito na mensagem

#### FA7 - Encaminhar mensagem

Usuário 1 encaminha uma mensagem que recebeu do usuário 2 para um terceiro usuário

#### FA8 - Enviar e abrir arquivos

Usuário 1 envia uma mensagem que possui um arquivo no formato PDF para o usuário 2, que o abre no próprio aplicativo após recebê-lo

#### FA9 - Enviar e editar imagem

Usuário 1 recorta uma imagem que achou na internet e a enviar para o usuário 2


### UC14 - Fazer Backup de mensagens
#### Fluxo Básico

O usuário 1 faz o backup das conversas que possui no aplicativo, salvando-as no Desktop pessoal dele

### UC15 - Fazer ligação
#### Fluxo Básico

Usuário 1 liga, por áudio, para o usuário 2

#### Fluxos Alternativos

#### FA1 - Ligar e desligar microfone

Durante a ligação de áudio, o usuário 1 desliga seu microfone para que os ruídos vindos do ambiente em que ele está não atrapalhe a reunião

#### FA2 - Entrar em ligação já existente

O usuário 3 se atrasa para uma reunião e, após chegar em um local com internet, entra na chamada que já estava sendo feita pelos outros usuários da reunião

#### FA4 - Fazer ligação de vídeo

Usuário 1 liga, por vídeo, para o usuário 2

#### FA5 - Ligar e desligar câmera

Durante a ligação de vídeo, o usuário 1 desliga sua câmera para que possa digitar a senha de um cofre que está atrás dele

#### FA6 - Adicionar pessoas à chamada

O usuário 1 inicia uma ligação de vídeo com o usuário 2 e adiciona o usuário 3, para que todos possam se comunicar diretamente

### UC22 - Criar grupo
#### Fluxo Básico

Usuário 1 cria um grupo vazio no aplicativo


#### Fluxos Alternativos

#### FA1 - Fazer um grupo de Transmissão de mensagens

O usuário 1 cria um grupo de transmissão de mensagens para que ele possa passar recados para outros membros da empresa

#### FA2 - Adicionar e remover pessoas do grupo

Usuário 1 adiciona o usuário 2 e o usuário 3 no grupo

#### FA3 - Definir permissões de cada membro

Usuário 1 aumenta as permissões do usuário 2, para que ele tenha mais autorizações no grupo

#### FA4 - Fixar mensagens

Usuário 1 manda uma mensagem sobre um evento importante da empresa e a fixa no grupo, para que todos a vejam

#### FA5 - Silenciar grupo

O usuário 2 silencia o grupo de mensagens que possui com seus amigos, pois o mesmo estava emitindo muitas notificações durante seu horário de serviço

#### FA6 - Enviar mensagem de alerta

Usuário 1 enviar uma mensagem de alerta no grupo, pois deseja a atenção de todos para a próxima mensagem que será enviada

#### FA7 - Responder mensagem recebida no grupo no privado

O usuário 2 responde uma mensagem do usuário 1 diretamente no privado, pois estava em dúvida sobre o que tinha sido dito, mas não queria falar sobre aquilo em público


### UC30 - Criar Guest Room
#### Fluxo Básico

Usuário 1 cria um Guest Room para que possa ter uma reunião com um cliente que não possui o aplicativo Wire na versão PRO

#### Fluxos Alternativos

#### FA1 - Gerar link externo para adicionar usuário

O usuário 1 gera um link web do Guest Room e o envia para seu cliente para que a reunião possa começar

### UC32 - Fazer cadastro
#### Fluxo Básico

Usuário 1 entra no aplicativo pela primeira vez e faz seu cadastro a partir do número de telefone utilizado e em seguida define o nome de usuário pelo qual será chamado

#### Fluxos Alternativos

#### FA1 - Fazer cadastro pelo e-mail

Usuário 1 entra no aplicativo pela primeira vez e faz seu cadastro a partir de um endereço de e-mail

#### FA2 - Criar time e adicionar usuários ao time

Usuário 1, após definir o nome de usuário, cria um time para sua empresa e adiciona os funcionários que já estão cadastrados no aplicativo

### UC38 - Adicionar contato de usuário
#### Fluxo Básico

Usuário 1 salva os dados do usuário 2 no aplicativo, a partir do e-mail do usuário 2

#### Fluxos Alternativos

#### FA1 - Editar dados do contato

Usuário 1 altera os dados salvos do usuário 2 e muda o nome com o qual o contato estava salvo

### UC40 - Bloquear usuário
#### Fluxo Básico

Usuário 1 bloqueia um usuário desconhecido que o mandou spans de sorteios

### UC41 - Editar perfil
#### Fluxo Básico

Usuário 1 alterou sua foto de perfil, pois a anterior era uma foto antiga

### UC42 - Alterar opção de download automático
#### Fluxo Básico

O usuário 1 está com pouca memória no celular e não quer mais baixar as imagens que recebe no aplicativo, para isso ele altera a opção de download automático

### UC43 - Deletar conta
#### Fluxo Básico

Usuário 1 não pretende mais utilizar o Wire e deleta a conta que possuia

### UC44 - Mudar senha
#### Fluxo Básico

Usuário 1, por motivos de segurança, altera a senha de sua conta mensalmente

**Comment by iurisevero** [comment]
O novo documento possui 44 casos de uso, 12 fluxos básicos e 25 fluxos alternativos
