### ISSUE TITLE
Modelagem - Melhoria Layout de Cenários.

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-de-Software/2019.2-Wire#47]
## Descrição da Issue
1. Seguindo o feedback da apresentação, deve-se melhorar e padronizar o tamanho dos títulos de cada cenário.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Melhorar layout da tela de cenários
- [x] Padronizar títulos dos cenários

### Critérios de aceitação
- [x] Validação com os membros do grupo.

**Comment by caiovfernandes** [comment]
Issue finalizada no PR: [https://github.com/Requisitos-de-Software/2019.2-Wire/pull/49](https://github.com/Requisitos-de-Software/2019.2-Wire/pull/49)
