### ISSUE TITLE
Elicitação - Documentar Brainstorm 

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#50]
## Descrição da Issue
Documentar o brainstorm realizado pela equipe na reunião do dia 30 de Setembro

### Tasks: 
- [x] Definir Brainstorming
- [x] Documentar reunião onde a elicitação foi feita
- [x] Criar página no github pages com o documento

### Critérios de aceitação
- [x] Documento estar legível, com tabela de versionamento e no local correto do site
