### ISSUE TITLE
Modelagem de Requisitos Ágil - NFR Framework

### ISSUE THREAD

**Issue by guilherme-mendes** [Requisitos-de-Software/2019.2-Wire#54]
## Descrição da Issue
Modelagem de Requisitos orientada à METAS.

### Tasks: 
- [x] Descrever todos os Requisitos Não-Funcionais (SOFTGOAL) do aplicativo Wire;
- [x] Modelo SIG (Grafos);
- [x] Critérios de Qualidade (Abstratas) / **Nuvem clara.**
- [x] Operacionalizações (Concretos, Verbos, Específicos). / **Nuvem escura.**
- [x] Claim (Justificativa) / **Nuvem pontilhada**.
- [x] Adicionar NFR desenvolvida à Wiki. 

### Critérios de aceitação:
- [x] Validação com o grupo.
- [x] Validação com o monitor.

**Comment by guilherme-mendes** [comment]
![image](https://user-images.githubusercontent.com/37874689/66833462-4239d380-ef32-11e9-951e-fec39ba64413.png)

**Comment by guilherme-mendes** [comment]
![image](https://user-images.githubusercontent.com/37874689/66833822-dc018080-ef32-11e9-9576-a9f55aa65936.png)

**Comment by guilherme-mendes** [comment]
Exemplos de NFR Framework:
* https://requisitos-habitica.netlify.com/NFR
* https://fga-disciplinas.github.io/2019.1-Guia-Bolso/modelagem/nfr/

**Comment by guilherme-mendes** [comment]
Rascunho do **NFR Framework**: 
![image](https://user-images.githubusercontent.com/37874689/66838799-b167f580-ef3b-11e9-993c-8c9cfe1d012e.png)

**Comment by sudjoao** [comment]
Versão feita até agora do NFR de usabilidade
![usabilidade_nfr](https://user-images.githubusercontent.com/46005310/66970941-9691a000-f065-11e9-9b25-49a40c55f398.png)
