### ISSUE TITLE
Modelagem de Requisitos Ágil - Backlog

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-de-Software/2019.2-Wire#55]
## Descrição da Issue
Desenvolver a documentação do backlog da aplicação Wire. O Product Backlog é uma lista contendo todas as funcionalidades desejadas para um produto.

### Tasks: 
- [x] Desenvolver Product Backlog.
- [x] Adicionar à wiki.
- [x] Adicioanr Hyperlink para os requisitos.

### Critérios de aceitação
- [x] Validação com o grupo.
- [x] Validação com o monitor.

**Comment by caiovfernandes** [comment]
## Exemplo de Backlog: 
<img width="893" alt="image" src="https://user-images.githubusercontent.com/42192251/66834859-d6a53580-ef34-11e9-8569-b200adbbe3cf.png">

**Comment by caiovfernandes** [comment]
## Exemplo de Backlog: 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/42192251/66835055-3ac7f980-ef35-11e9-8f36-f38b191e203a.png">

**Comment by caiovfernandes** [comment]
![BacklogDiagram](https://user-images.githubusercontent.com/42192251/67004237-3aa33780-f0b6-11e9-9e47-d72e276c5641.png)

**Comment by caiovfernandes** [comment]
![RQS](https://user-images.githubusercontent.com/42192251/67007682-4f83c900-f0be-11e9-8a3c-38d9f0df3ca0.png)

**Comment by caiovfernandes** [comment]
![RQS2](https://user-images.githubusercontent.com/42192251/67008266-8d352180-f0bf-11e9-9b9e-833331f16ff0.jpg)

**Comment by caiovfernandes** [comment]
![RQS3](https://user-images.githubusercontent.com/42192251/67009479-19e0df00-f0c2-11e9-8d57-9d0f8d7e2b95.jpg)
