### ISSUE TITLE
Verificação -  Criar documento de verificação do NFR

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#59]
## Descrição da Issue
- Criar documento de verificação do NFR embasado no conteúdo apresentado em sala.

### Tasks: 
- [x] Criar checklist de verificação
- [ ] Verificar NFR's a partir do checklist criado
- [ ] Criar um documento com os dados adquiridos a partir da verificação

### Critérios de aceitação
- [x] Checklist deve ter embasamento válido
- [ ] Os dados do que precisa ser alterado deve ser descrito no documento
- [ ] Documento estar disponível no GitHub Pages

**Comment by iurisevero** [comment]
## Checklist de verificação

* Cada softgoal possui um tipo e um tópico?
* Softgoals abstratos são decompostos em subtópicos com softgoals mais específicos?
* Softgoals são decompostos em operacionalizações?
* As operacionalizações podem ser usadas como especificações do sistema?
* As operacionalizações podem ser selecionadas para garantir um resultado viável do sistema?
* A direção da interdependência entre operacionalizações e softgoals vai do mais concreto para o mais abstrato?
* Há a adição de claims para justificar os softgoals quando necessário?
* Contribuições and somente entre softgoals?
* Contribuições or somente entre softgoals?
* Contribuições positivas somente entre os softgoals e as operacionalizações?
* Contribuições negativas somente entre os softgoals e as operacionalizações?
* Os softgoals e as operacionalizações foram classificados a partir de labels?
* A propagação das labels foi feita corretamente?


## Referência
* [Extending the NFR Framework with Measurable NonFunctional Requirements](https://pdfs.semanticscholar.org/4ab6/c7def9be016130684ae615d5bd6ae0e04992.pdf)
* Goal Achievement Evaluation in the NFR Framework, by Sam Supakkul and Lawrence Chung

**Comment by iurisevero** [comment]
## NFR Usabilidade
|Item|Cumpre o critério|Quantidade de Erros|Tipo de Erro|Correção possível|
|---|---|---|---|---|
|Cada softgoal possui um tipo e um tópico?| Não | 6/8 | 1 | Adicionar tópicos aos softgoals|
|Softgoals abstratos são decompostos em subtópicos com softgoals mais específicos?|  Sim | 0/5 | - | - |
|Softgoals são decompostos em operacionalizações?| Sim | 0/8 | - | - | 
|As operacionalizações podem ser usadas como especificações do sistema?| Não | 4/12 | 1 | Decompor mais as operacionalizações |
|As operacionalizações podem ser selecionadas para garantir um resultado viável do sistema?| Sim | 0/12 | - | - |
|A direção da interdependência entre operacionalizações e softgoals vai do mais concreto para o mais abstrato?| Não | 19/21 | 1 | Adicionar indicação de direção em todas interdependências |
|Há a adição de claims para justificar os softgoals quando necessário?| Sim | 0/8 | - | - |
|Contribuições and somente entre softgoals?| Sim | 0/7 | - | - |
|Contribuições or somente entre softgoals?| Sim | 0/7 | - | - |
|Contribuições positivas somente entre os softgoals e as operacionalizações?| Não | 12/14 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Contribuições negativas somente entre os softgoals e as operacionalizações?| Não | 12/14 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Os softgoals e as operacionalizações foram classificados a partir de labels?| Sim | 0/20 | - | - |
|A propagação das labels foi feita corretamente?| Não | 2/20 | 1 | Corrigir label gerada nos pontos especificados |

* **Item 1:** Usabilidade, Suporte adequado ao usuário, Facilidade de Uso, Ser intuitivo, Interface agradável, Bom desempenho;

* **Item 4:** Ter ações bem definidas, Ter uma interface simples, Prevenção de erros, Tratamento de erros;

* **Item 13:** Suporte adequado ao usuário, Sistema agradável

**Comment by iurisevero** [comment]
## NFR Eficiência
|Item|Cumpre o critério|Quantidade de Erros|Tipo de Erro|Correção possível|
|---|---|---|---|---|
|Cada softgoal possui um tipo e um tópico?| Não | 6/12 | 1 | Adicionar tópicos aos softgoals listados|
|Softgoals abstratos são decompostos em subtópicos com softgoals mais específicos?|  Sim | 0/12 | - | - |
|Softgoals são decompostos em operacionalizações?| Sim | 0/8 | - | - | 
|As operacionalizações podem ser usadas como especificações do sistema?| Sim | 0/14 | - | - |
|As operacionalizações podem ser selecionadas para garantir um resultado viável do sistema?| Sim | 0/14 | - | - |
|A direção da interdependência entre operacionalizações e softgoals vai do mais concreto para o mais abstrato?| Não | 3/16 | 1 | Verificar interdependências listadas |
|Há a adição de claims para justificar os softgoals quando necessário?| Não | 2/12 | - | - |
|Contribuições and somente entre softgoals?| Não | 1/12 | 1 | Adicionar contribuições nos softgoals indicados |
|Contribuições or somente entre softgoals?| Não | 2/12 | 1 | Adicionar contribuições nos softgoals indicados |
|Contribuições positivas somente entre os softgoals e as operacionalizações?| Não | 12/16 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Contribuições negativas somente entre os softgoals e as operacionalizações?| Não | 12/16 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Os softgoals e as operacionalizações foram classificados a partir de labels?| Sim | 0/26 | - | - |
|A propagação das labels foi feita corretamente?| Não | 2/26 | 1 | Corrigir label gerada nos pontos especificados |

* **Item 1:** Eficiência, Performance, Armazenamento, Otimização do tempo de respostas, Portabilidade, Disponibilidade de autenticações 
* **Item 6:** Acessos simultâneos -> Mostrar dados atualizados, Serviços externos -> Plaforma Web, Serviços Externos -> Dispositivo Mobile
* **Item 9:** Armazenamento, Serviços Externos (a Claim está apontada para o local errado)
* **Item 10:** Tecnologias apropriadas
* **Item 11:** Mobile, Web
* **Item 13:** Performance, Portabilidade

**Comment by iurisevero** [comment]
## NFR Confiabilidade
|Item|Cumpre o critério|Quantidade de Erros|Tipo de Erro|Correção possível|
|---|---|---|---|---|
|Cada softgoal possui um tipo e um tópico?| Não | 2/7 | 1 | Adicionar tópicos aos softgoals listados|
|Softgoals abstratos são decompostos em subtópicos com softgoals mais específicos?|  Sim | 0/7 | - | - |
|Softgoals são decompostos em operacionalizações?| Sim | 0/5 | - | - | 
|As operacionalizações podem ser usadas como especificações do sistema?| Sim | 0/15 | - | - |
|As operacionalizações podem ser selecionadas para garantir um resultado viável do sistema?| Sim | 0/15 | - | - |
|A direção da interdependência entre operacionalizações e softgoals vai do mais concreto para o mais abstrato?| Não | 17/17 | 1 | Verificar todas interdependências de operacionalizações e softgoals |
|Há a adição de claims para justificar os softgoals quando necessário?| Sim | 0/7 | - | - |
|Contribuições and somente entre softgoals?| Não | 10/22 | 1 | Verificar contribuições nas operacionalizações |
|Contribuições or somente entre softgoals?| Não | 10/22 | 1 | Verificar contribuições nas operacionalizações |
|Contribuições positivas somente entre os softgoals e as operacionalizações?| Não | 17/17 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Contribuições negativas somente entre os softgoals e as operacionalizações?| Não | 17/17 | 1 | Adicionar contribuições a todas interdependências de operacionalizações com softgoals |
|Os softgoals e as operacionalizações foram classificados a partir de labels?| Sim | 0/22| - | - |
|A propagação das labels foi feita corretamente?| Não | 4/22 | 1 | Corrigir label gerada nos pontos especificados |

* **Item 1:** Segurança, Autenticação 
* **Item 13:** BackUp manual, Autenticação, Controle de dispositivos, Recuperabilidade de dados

**Comment by iurisevero** [comment]
## Tipos de Erro

|Código|Tipo de Erro|Descrição|
|---|---|---|
| 1 | Defeito de Omissão | Informações necessárias ao sistema são omitidas |
| 2 | Defeito de Fato Incorreto | Há informações nos artefatos do sistema que são contraditórios com o domínio da aplicação |
| 3 | Inconsistência | Informação aparece mais de uma vez de formas diferentes |
| 4 | Ambiguidade | Informação leva múltiplas interpretações |
| 5 | Defeito de Informação Estranha | Informação que aparece no artefato e, embora relacionada, não é necessária para o sistema |
