### ISSUE TITLE
Verificação - Casos de Uso

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-de-Software/2019.2-Wire#61]
### Descrição da Issue
Verificar e validar casos de uso de acordo com algum material de referência.

### Tasks: 
- [x] Encontrar material (artigos, livros, publicações...) sobre casos de uso para utilizar como referência.
- [ ] Validar os casos de uso.
- [ ] Criar documento de verificação para casos de uso.

### Critérios de aceitação
- [ ] Validação realizada estar de acordo com material de referência.
- [ ] Ter todo o processo documentado.
- [ ] Adicionar todos os artefatos colhidos à Wiki.

**Comment by caiovfernandes** [comment]
## Checklist de verificação

- O caso de uso organiza requisitos funcionais?
- Traz valor observável e contexto, organizados de acordo com a visão do usuário?
- Descreve o que o sistema deve fazer, expressando os passos interativos que o usuário deve performar para alcançar um resultado de valor?
- Traz um diagrama de fluxos textual, especificando ações no fluxo?
- O diagrama textual define como as partes dos casos de uso se encaixam?
- Possui um fluxo principal único e vários fluxos alternativos ?
- Usa de referencias para explicitar o começo e o fim de um fluxo alternativo, referenciando um passo específico dentro do fluxo principal ou mesmo em um  fluxo alternativo ?
- Referencias ocorrem apenas no fluxo secundário?
- Ator escolhe um caminho como fluxo principal e os outros são fluxos secundários?

## Referências
 - James Heumann, IBM Rational Software. Tips for writing good use cases. Disponível em : [ftp.software.ibm.com/software/rational/web/whitepapers](http://ftp.software.ibm.com/software/rational/web/whitepapers/RAW14023-USEN-00.pdf). Acesso em 28 de outubro de 2019.
- Marilyn Bush, Chris Gerrard, Clifford Shelley. Fagan Inspection: The Silver Bullet No-one Wants to Fire. Disponível em: [http://www.osel.co.uk/presentations/fitsbnwtf.pdf](http://www.osel.co.uk/presentations/fitsbnwtf.pdf). Acesso em 28 de outubro de 2019.

**Comment by caiovfernandes** [comment]
![user_cases_verification](https://user-images.githubusercontent.com/42192251/68148057-0c2cb580-ff1a-11e9-8390-449bb65ac2c7.jpg)

**Comment by caiovfernandes** [comment]
![user_cases_verification](https://user-images.githubusercontent.com/42192251/68148460-cd4b2f80-ff1a-11e9-9774-5efae9b74251.jpg)

**Comment by caiovfernandes** [comment]
<img width="619" alt="1" src="https://user-images.githubusercontent.com/42192251/68149553-d806c400-ff1c-11e9-8176-704131e4d2cb.png">
<img width="647" alt="2" src="https://user-images.githubusercontent.com/42192251/68149555-d806c400-ff1c-11e9-9fac-58e557d2e7ee.png">
<img width="702" alt="3" src="https://user-images.githubusercontent.com/42192251/68149556-d89f5a80-ff1c-11e9-8b96-e8ce6bd3b3b3.png">
<img width="705" alt="4" src="https://user-images.githubusercontent.com/42192251/68149557-d89f5a80-ff1c-11e9-8e47-1ce2a4fafd46.png">
![Uploading 5.png…]()
![Uploading 6.png…]()
![Uploading 7.png…]()
![Uploading 8.png…]()
![Uploading 9.png…]()
![Uploading 10.png…]()

**Comment by caiovfernandes** [comment]
<img width="619" alt="1" src="https://user-images.githubusercontent.com/42192251/68149576-dfc66880-ff1c-11e9-9d0c-b0b96ec5d275.png">
<img width="647" alt="2" src="https://user-images.githubusercontent.com/42192251/68149577-dfc66880-ff1c-11e9-9fe7-085f878bf5af.png">
<img width="702" alt="3" src="https://user-images.githubusercontent.com/42192251/68149579-dfc66880-ff1c-11e9-8c8f-24c30f8704ec.png">
<img width="705" alt="4" src="https://user-images.githubusercontent.com/42192251/68149580-e05eff00-ff1c-11e9-8e36-59a64fa7bfcf.png">
<img width="662" alt="5" src="https://user-images.githubusercontent.com/42192251/68149581-e05eff00-ff1c-11e9-98fd-04fe9da8dc04.png">
<img width="663" alt="6" src="https://user-images.githubusercontent.com/42192251/68149582-e05eff00-ff1c-11e9-9c57-07c3fa5b77bb.png">
<img width="671" alt="7" src="https://user-images.githubusercontent.com/42192251/68149583-e0f79580-ff1c-11e9-85b8-0a0f718b1c87.png">
<img width="705" alt="8" src="https://user-images.githubusercontent.com/42192251/68149584-e0f79580-ff1c-11e9-8b3a-9ef778965db0.png">
<img width="676" alt="9" src="https://user-images.githubusercontent.com/42192251/68149585-e0f79580-ff1c-11e9-9993-f688e4af9806.png">
<img width="675" alt="10" src="https://user-images.githubusercontent.com/42192251/68149587-e0f79580-ff1c-11e9-9b07-c662af89922e.png">

**Comment by caiovfernandes** [comment]
James Heumann, IBM Rational Software. Tips for writing good use cases. Disponível em : ftp.software.ibm.com/software/rational/web/whitepapers. Acesso em 28 de outubro de 2019.

Ivar Jacobson, Ian Spence, Kurt Bittner. USE-CASE 2.0,The Guide to Succeeding with Use Cases.

**Comment by caiovfernandes** [comment]
![logo3](https://user-images.githubusercontent.com/42192251/68207814-8a3a9c00-ffae-11e9-92fc-9d1c6903a68f.jpg)

**Comment by caiovfernandes** [comment]
![logo2](https://user-images.githubusercontent.com/42192251/68207846-9fafc600-ffae-11e9-941e-f576a03c345e.jpg)

**Comment by caiovfernandes** [comment]
![logo](https://user-images.githubusercontent.com/42192251/68207914-ca9a1a00-ffae-11e9-98e8-7bb698756e47.jpg)
