### ISSUE TITLE
Verificação - Rich Picture

### ISSUE THREAD

**Issue by guilherme-mendes** [Requisitos-de-Software/2019.2-Wire#62]
### Tasks: 
- [x] Verificação das versões dos Rich Picture.
- [x] Adicionar a wiki.
- [x] Embasamento em referências bibliográficas.

### Critérios de aceitação
- [x] Validar com o grupo e monitor.
