### ISSUE TITLE
Verificação - Criar documento de verificação dos cenários

### ISSUE THREAD

**Issue by lucasfcm9** [Requisitos-de-Software/2019.2-Wire#63]
## Descrição da Issue
* Criar documento de verificação dos cenários embasado no conteúdo apresentado em sala de aula.

### Tasks: 
- [x] Criar *checklist* de verificação;
- [x] Verificar todos os cenários a partir do *checklist* criado;
- [x] Criar um documento com todos os dados adquiridos e colocá-lo na wiki.

### Critérios de aceitação

- [x] Checklist deve possuir embasamento válido;
- [x] A documentação com todos os dados precisa estar disponível na wiki.

**Comment by lucasfcm9** [comment]
Checklist:
* O título é auto-explicativo;
* O objetivo é claro;
* O contexto apresenta pré-condição;
* A pré condição está completa;
* O contexto apresenta local;
* O contexto apresenta tempo
* Os atores foram listados da forma correta
* Existem recursos;
* Os episódios abrangem todo o processo;
* Os episódios estão claros;
* Existem restrições;
* Existem exceções;
* Possui hyperlinks.

**Comment by lucasfcm9** [comment]
![Tabela cenários requisitos](https://user-images.githubusercontent.com/40740008/67860673-3981f980-fafd-11e9-9025-0f6cb3b34ccf.jpg)

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 14 49 59" src="https://user-images.githubusercontent.com/40740008/67884627-ed4aaf80-fb24-11e9-8ec6-59bc5a13d4b4.png">

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 14 56 05" src="https://user-images.githubusercontent.com/40740008/67884923-6c3fe800-fb25-11e9-8b79-2e23eaaf4d76.png">

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 15 02 21" src="https://user-images.githubusercontent.com/40740008/67885402-4b2bc700-fb26-11e9-897c-a528cf1f67c7.png">

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 15 03 51" src="https://user-images.githubusercontent.com/40740008/67885513-8201dd00-fb26-11e9-9dfa-973dca691e16.png">

**Comment by lucasfcm9** [comment]
<img width="347" alt="Screen Shot 2019-10-30 at 15 14 46" src="https://user-images.githubusercontent.com/40740008/67886343-10c32980-fb28-11e9-8fb4-539499a5e3cf.png">

**Comment by lucasfcm9** [comment]
<img width="353" alt="Screen Shot 2019-10-30 at 15 16 48" src="https://user-images.githubusercontent.com/40740008/67886511-5122a780-fb28-11e9-85a2-9f40b833f077.png">

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 15 16 48" src="https://user-images.githubusercontent.com/40740008/67886528-5849b580-fb28-11e9-8b96-ae3ac33e79fb.png">

**Comment by lucasfcm9** [comment]
<img width="349" alt="Screen Shot 2019-10-30 at 15 19 59" src="https://user-images.githubusercontent.com/40740008/67886739-c0989700-fb28-11e9-8c95-a7401eeeef20.png">

**Comment by lucasfcm9** [comment]
![erros_fagan](https://user-images.githubusercontent.com/40740008/67889473-b1681800-fb2d-11e9-9417-8b0d5289b154.jpg)
