### ISSUE TITLE
Verificacao - Especificação Suplementar

### ISSUE THREAD

**Issue by gitgabiru** [Requisitos-de-Software/2019.2-Wire#66]
### Tasks: 
- [x] Verificação das versões da Especificação Suplementar.
- [x] Adicionar a wiki.
- [x] Embasamento em referências bibliográficas.

### Critérios de aceitação
- [ ] Validar com o grupo e monitor.

**Comment by gitgabiru** [comment]
![Inspecao_Esp_Suplementar](https://user-images.githubusercontent.com/26935152/68078168-82f96f80-fdaf-11e9-9732-d99825ceccd7.png)

**Comment by gitgabiru** [comment]
![Screenshot from 2019-11-03 18-09-28](https://user-images.githubusercontent.com/26935152/68091972-1e005100-fe65-11e9-9c42-fbfc0430e5c0.png)

**Comment by gitgabiru** [comment]
![Screenshot from 2019-11-03 18-12-20](https://user-images.githubusercontent.com/26935152/68092017-83ecd880-fe65-11e9-9a8e-cb7cfa90b8e8.png)

**Comment by gitgabiru** [comment]
![a](https://user-images.githubusercontent.com/26935152/68147164-3d0beb00-ff18-11e9-8fef-b93cdc9fcb40.png)

**Comment by gitgabiru** [comment]
![b](https://user-images.githubusercontent.com/26935152/68147199-53b24200-ff18-11e9-900a-f982d4028ecd.png)

**Comment by gitgabiru** [comment]
![c](https://user-images.githubusercontent.com/26935152/68147211-5d3baa00-ff18-11e9-8718-a7d74ff109db.png)
