### ISSUE TITLE
Validação - Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#68]
## Descrição da Issue
Criar um protótipo de alta fidelidade baseado nos requisitos levantados

### Tasks: 
- [x] Criar telas descritas no requisitos
- [x] Abranger requisitos não funcionais e funcionais

### Critérios de aceitação
- [x] Seguir a paleta de cores do produto
- [x] Grupo aprovar o protótipo
