### ISSUE TITLE
Verificação - Ágil

### ISSUE THREAD

**Issue by sudjoao** [Requisitos-de-Software/2019.2-Wire#69]
## Descrição da Issue
Verificar, utilizando referências bibliográficas, a modelagem ágil feita no projeto.
### Tasks: 
- [x] Encontrar artigos ou livros para se basear;
- [x] Levantar quais são os critérios de avaliação;
- [x] Verificar o modelo ágil.

### Critérios de aceitação
- [x] Fazer a verificação de todo o modelo ágil;
- [x] Citar as referências bibliográficas;
- [x] Gerar dados sobre a verificação.

**Comment by sudjoao** [comment]
A principal referência bibliográfica que está sendo utilizada na verificação do ágil é o livro **Scrum, a arte de fazer o dobro do trabalho na metade do tempo**, escrito por &&Jeff Sutherland** e **JJ. Sutherland**.
