### ISSUE TITLE
Verificação - Léxicos (objetos)

### ISSUE THREAD

**Issue by gitgabiru** [Requisitos-de-Software/2019.2-Wire#72]
### Tasks: 
- [x] Verificação das versões do Léxico.
- [x] Adicionar a wiki.
- [x] Embasamento em referências bibliográficas.

### Critérios de aceitação
- [x] Validar com o grupo e monitor.

**Comment by gitgabiru** [comment]
![possuiNocao](https://user-images.githubusercontent.com/26935152/68178623-7457b780-ff6b-11e9-9d53-90df89fcbd1a.png)

**Comment by gitgabiru** [comment]
![possuiImpacto](https://user-images.githubusercontent.com/26935152/68178632-7de11f80-ff6b-11e9-892b-1e77351c5abd.png)

**Comment by gitgabiru** [comment]
![3](https://user-images.githubusercontent.com/26935152/68178638-83d70080-ff6b-11e9-916e-3d6bc18c108d.png)

**Comment by gitgabiru** [comment]
![4](https://user-images.githubusercontent.com/26935152/68178642-8a657800-ff6b-11e9-9c65-4cb470e89f48.png)

**Comment by gitgabiru** [comment]
![5](https://user-images.githubusercontent.com/26935152/68178644-8fc2c280-ff6b-11e9-84cd-6a75160d3cff.png)

**Comment by gitgabiru** [comment]
![6](https://user-images.githubusercontent.com/26935152/68178651-96513a00-ff6b-11e9-9307-ea01cab4f7e1.png)

**Comment by gitgabiru** [comment]
![7](https://user-images.githubusercontent.com/26935152/68178660-9cdfb180-ff6b-11e9-9ad8-aae1684abd2f.png)
