### ISSUE TITLE
Refatorar Backlog

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#78]
## Descrição da Issue
Refatorar as User Stories de acordo com a [verificação descrita na wiki](https://requisitos-de-software.github.io/2019.2-Wire/#/docs/verification/Agile/agile)

### Tasks: 
- [x] Refatorar US
- [x] Adicionar critérios de aceitação
- [ ] Adicionar priorização
- [ ] Estimular esforço de cada atividade

### Critérios de aceitação
- [ ] Os artefatos refatorados estarem de acordo com a verificação realizada

**Comment by iurisevero** [comment]
Diagrama do Backlog v2
![Diagrama do Backlog v2](https://user-images.githubusercontent.com/42645264/69480636-0bd05d80-0de8-11ea-824f-d17257faf6b2.png)

**Comment by lucasfcm9** [comment]
![ProductBacklog](https://user-images.githubusercontent.com/40740008/69480596-8a78cb00-0de7-11ea-9849-b33189e80a60.jpg)
