### ISSUE TITLE
Criar tabela de Backward-from

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-de-Software/2019.2-Wire#79]
## Descrição da Issue
Criar tabela de pós-rastreabilidade utilizando a técnica Backward-from, descrita nos materiais fornecidos pelo professor

### Tasks: 
- [x] Criar tabela Backward-from
- [x] Criar documento na wiki contento explicações sobre a pós-rastreabilidade e a tabela

### Critérios de aceitação
- [x] Documento estar completo e coerente

**Comment by caiovfernandes** [comment]
## Referências
 - Milene Serrano, Maurício Serrano. Requisitos – Aula 26. Disponível em : [https://aprender.ead.unb.br/pluginfile.php/730439/mod_resource/content/1/Requisitos%20-%20Aula%20026.pdf](https://aprender.ead.unb.br/pluginfile.php/730439/mod_resource/content/1/Requisitos%20-%20Aula%20026.pdf). Acesso em 16 de novembro de 2019.
- Miriam Sayão, Julio Cesar Sampaio do Prado Leite. Rastreabilidade de Requisitos. Disponível em: [http://www.dbd.puc-rio.br/depto_informatica/05_20_sayao.pdf](http://www.dbd.puc-rio.br/depto_informatica/05_20_sayao.pdf).  Acesso em 16 de novembro de 2019.
