### ISSUE TITLE
Criar tabela de Foward-from

### ISSUE THREAD

**Issue by sudjoao** [Requisitos-de-Software/2019.2-Wire#80]
## Descrição da Issue
Criar tabela de pós-rastreabilidade utilizando a técnica Foward-from, descrita nos materiais fornecidos pelo professor

### Tasks: 
- [x] Criar tabela Foward-from
- [x] Criar documento na wiki contendo explicações sobre a pós-rastreabilidade e a tabela

### Critérios de aceitação
- [x] Documento estar completo e coerente
